dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  file_picker: ^6.1.1
  permission_handler: ^11.3.0
  camera: ^0.10.5
  path_provider: ^2.0.15
  http: ^0.13.5
  video_player: ^2.7.2
  flutter_spinkit: ^5.1.0
